# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/mondial.xerml.xml" -l "../../xml/mondial.xerml.lo.xml" -o "mondial_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/mondial.xerml.xml" -o "mondial.graphml" -g)
