# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/rettungsstelle.xerml.xml" -l "../../xml/rettungsstelle.xerml.lo.xml" -o "rettungsstelle_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/rettungsstelle.xerml.xml" -o "rettungsstelle.graphml" -g)
