# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/aaa.xerml.xml" -l "../../xml/aaa.xerml.lo.xml" -o "aaa_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/aaa.xerml.xml" -o "aaa.graphml" -g)
