# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/weingut.xerml.xml" -l "../../xml/weingut.xerml.lo.xml" -o "weingut_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/weingut.xerml.xml" -o "weingut.graphml" -g)
