# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/kinokette.xerml.xml" -l "../../xml/kinokette.xerml.lo.xml" -o "kinokette_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/kinokette.xerml.xml" -o "kinokette.graphml" -g)
