# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/fußball.xerml.xml" -l "../../xml/fußball.xerml.lo.xml" -o "fußball_en.graphml" -g )

$(shell ermtk erdgenerate -i "../../xml/fußball.xerml.xml" -o "fußball.graphml" -g )
