# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/sf.xerml.xml" -l "../../xml/sf.xerml.lo.xml" -o "sf_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/sf.xerml.xml" -o "sf.graphml" -g)
