# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/tankstelle.xerml.xml" -l "../../xml/tankstelle.xerml.lo.xml" -o "tankstelle_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/tankstelle.xerml.xml" -o "tankstelle.graphml" -g)
