# Makefile.rules im Top-Level-Verzeichnis

$(shell ermtk erdgenerate -i "../../xml/sis.xerml.xml" -l "../../xml/sis.xerml.lo.xml" -o "sis_en.graphml" -g)

$(shell ermtk erdgenerate -i "../../xml/sis.xerml.xml" -o "sis.graphml" -g)
